tasks:
  - init: echo "Replace me with a build script for the project."
    command: pip3 install cassandra-driver
    command: pip3 install requests
    command: cd Data\ Migrator/
image:
  file: .gitpod.Dockerfile
